"""empty message

Revision ID: 6d7d283707a8
Revises: 3ead48a37e21
Create Date: 2023-07-12 07:06:53.206614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d7d283707a8'
down_revision = '3ead48a37e21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite', sa.Boolean(), server_default='false', nullable=False), schema='fansly')
    op.add_column('users', sa.Column('favorite', sa.Boolean(), server_default='false', nullable=False), schema='onlyfans')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite', schema='onlyfans')
    op.drop_column('users', 'favorite', schema='fansly')
    # ### end Alembic commands ###
